### ISSUE TITLE
make a workflow in galaxy

### ISSUE THREAD

**Issue by volodymyrss** [esg-epfl-apc/tools-astro#135]
workflow will look like:
 
1. input atel text
2. extract source name
3. find DESI photometry
4. apply photoz, get redshift

**Comment by Andrei-EPFL** [comment]
@volodymyrss ,  I made the first version and the first step of the workflow (now it has the image, but anyway the DESI fails due to the oda-api version https://github.com/oda-hub/oda_api/issues/303):

https://galaxy.odahub.fr/u/andreiv/w/atel-follow-up-photometric-data-legacy-survey

I will check whether there tools that can iterate through the detected sources.

**Comment by Andrei-EPFL** [comment]
@volodymyrss  This is the workflow that includes the text analysis pipeline, the DESI legacy survey photometric data extraction and the EUCLID photo-z  one. 
I will have to check different cases and put some specific errors when needed. In principle the workflow works now.
I also managed to send the dictionary of filters in the DESI LS notebook as an output
