### ISSUE TITLE
add support for visualizing FITS images and tables ESG-WP5

### ISSUE THREAD

**Issue by volodymyrss** [esg-epfl-apc/tools-astro#3]
An example is https://github.com/galaxyproject/galaxy/pull/15394

**Comment by volodymyrss** [comment]
we should try to use https://aladin.u-strasbg.fr/AladinLite/doc/ specifically v3

**Comment by francoismg** [comment]
Here's what the aladin lite viewer integration in galaxy looks like. I load the specified fits file directly in the plugin so no user interaction is necessary.

The dimensions and position of the viewer can obviously be customised, here I make it use all the width at its disposal. 

Since the viewer is embed into galaxy the fullscreen option is limited to the plugin window size but otherwise everything seems to be working as with a regular integration.

<img width="1424" alt="aladinlite1" src="https://github.com/esg-epfl-apc/tools-astro/assets/46478217/fcbef83a-66bb-41ea-aed6-5a66fe1e42f8">

By loading the image directly at startup the provided fits file is used as a base layer so none of the preexisting base layer are used.

There's also an array of settings you can use to modify the way the file is displayed. Most of those settings can be hidden at startup or set to some values programmatically if needed.

I have tried to change some settings like colormap, contrast, etc and they seem to be working fine.

<img width="833" alt="aladinlite2" src="https://github.com/esg-epfl-apc/tools-astro/assets/46478217/6e483db1-47da-4c8a-9c2a-7ef53a1ec27d">
<img width="835" alt="aladinlite3" src="https://github.com/esg-epfl-apc/tools-astro/assets/46478217/0494400b-5ff4-4cba-82f5-99c9bcdbc98b">

Regarding the sky coordinates they seem to change based on what fits file are loaded, whether it's a base image or an additional image. (The healpix grid coordinates are changing too)

I saw that the horsehead nebula coordinates (declination?) are −02° 27′ 30.0" and I have something similar when loading an horsehead nebula fits file so it might indicate that the coordinates are working too.

<img width="422" alt="aladinlite10" src="https://github.com/esg-epfl-apc/tools-astro/assets/46478217/92710269-67ad-4898-b051-5d9d65c1ea13">

<img width="420" alt="aladinlite9" src="https://github.com/esg-epfl-apc/tools-astro/assets/46478217/afbf3da9-4169-4119-8f2d-dbbef47611ab">


The viewer comes with a set of layers that can be used too. Not sure if useful or relevant but I'm not sure that we can hide these without hiding other settings.

<img width="470" alt="aladinlite5" src="https://github.com/esg-epfl-apc/tools-astro/assets/46478217/a77116ad-eb0b-4fdd-a912-3cba77433747">

There's also the possibility to navigate to a specific object inside a file (you can also create object programmatically if I'm not mistaken) but I think that's only working when using hips file.

<img width="268" alt="aladinlite6" src="https://github.com/esg-epfl-apc/tools-astro/assets/46478217/d81d7404-cb61-4172-b549-cb3b34879cd3">

I tried the viewer with a few different fits file including the legacy-survey available in the astro-tools repo and they seemed all to be working.

<img width="838" alt="aladinlite8" src="https://github.com/esg-epfl-apc/tools-astro/assets/46478217/64fa1645-3eeb-4ed7-ba2e-08351ad67367">

<img width="836" alt="aladinlite7" src="https://github.com/esg-epfl-apc/tools-astro/assets/46478217/daecf0e7-0047-4bae-91f9-028eb5d2dfae">


**API**

The aladin lite javascript api doesn't offer that much possibilities but maybe it's enough. It's possible to manage layers programmatically, load pixel values for specific coordinates, hide/change most of the settings available to the user, create specific markers on the map, create specific shapes (polyline, circle, etc), and you can also directly load images from SIMBAD and other providers.

**Export**

You also have the possibility to create a png from the current view directly with the ui or programmatically.

**Documentation**

The documentation isn't that big and a few bit could be out of date or misleading (like the fact that they say that they don't natively support fits file) :

> While Aladin Lite currently does not support natively, small FITS images can be visualized by converting them server-side to HiPS under the hood using the displayFITS(<FITS-URL>) method.

I thought it might indicate that the viewer is using their converting tool api to convert fits file into something else before loading the file but I didn't see any network call that looked like that and I didn't find some conversion thing in the js code (but maybe I have just skipped it) so I guess we can just disregard that as it seems to be working fine

**Error handling**

When the viewer cannot parse a specific fits file it outputs an error message in an alert box which might not be the most user friendly way but apparently even if it's not specified in the documentation I saw by looking at the code that we might specify a callback in case the parsing encounters some error

`Aladin.prototype.displayFITS = function (url, options, successCallback, errorCallback, layer = "base")`

So if we can set the callback to a function outside of aladin we could manage errors in a more user friendly fashion

**Comment by volodymyrss** [comment]
Looks very good, thanks! We need to try it live to see a bit if it has all we need, but it seems so. Do you want to make a PR?

**Comment by francoismg** [comment]
I will need to package it first but yes we can open a PR on galaxy. Since it's a plugin I wasn't sure if the goal was to make it like a core galaxy plugin that will be available in every galaxy install by making a PR or if the plugin would just be made available and then installed independently by user who would need it

**Comment by volodymyrss** [comment]
> I will need to package it first but yes we can open a PR on galaxy. Since it's a plugin I wasn't sure if the goal was to make it like a core galaxy plugin that will be available in every galaxy install by making a PR or if the plugin would just be made available and then installed independently by user who would need it

My assumption was that we do like in the example given to us by @bgruening , the one quoted at the top, this https://github.com/galaxyproject/galaxy/pull/15394 . It's contributing to the core code, right?

**Comment by francoismg** [comment]
> > I will need to package it first but yes we can open a PR on galaxy. Since it's a plugin I wasn't sure if the goal was to make it like a core galaxy plugin that will be available in every galaxy install by making a PR or if the plugin would just be made available and then installed independently by user who would need it
> 
> My assumption was that we do like in the example given to us by @bgruening , the one quoted at the top, this [galaxyproject/galaxy#15394](https://github.com/galaxyproject/galaxy/pull/15394) . It's contributing to the core code, right?
> 
> edit: if @bgruening has some insights they are welcome

Yes that one would be available in every galaxy install if I'm not mistaken. Ok so let's do it like that then no problem

**Comment by francoismg** [comment]
https://github.com/galaxyproject/galaxy/pull/16187 has been tested and merged by the galaxy team

**Comment by bgruening** [comment]
Can this one be closed?
